name: CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

  lint:
    needs: setup
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1

  test:
    needs: setup
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: make test

  build:
    needs: [lint, test]
    name: Build
    runs-on: ubuntu-last
    steps:
      - name: Build
        run: make build
