name: CI

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1
      - name: Run Tests
        run: make test
      - name: Build
        run: make build
